spring:
  liquibase:
    change-log: classpath:changelogs/master.xml
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
server:
  servlet:
    session:
      cookie:
        name: ''
